/**
 * @module models/Dashboard
 * @description Mongoose schema and model for dashboard ownership, visibility, and sharing.
 */

import crypto from "node:crypto";
import mongoose from "mongoose";
import { ObjectId } from "mongodb";
import { nanoid } from "nanoid";
import {
  DASHBOARD_ACCESS_LEVELS,
  DASHBOARD_VISIBILITIES,
} from "../policy.js";

/**
 * @typedef {Object} MongooseSchema
 *   Alias for mongoose.Schema
 * @typedef {Object} MongooseModel
 *   Alias for mongoose.Model
 */

const Schema = mongoose.Schema;

const generateShareToken = () => crypto.randomBytes(24).toString("base64url");

/**
 * Ensure ObjectId valueOf returns string representation.
 */
ObjectId.prototype.valueOf = function () {
  return this.toString();
};

/**
 * Dashboard document schema.
 *
 * @typedef {Object} DashboardDoc
 * @property {string} _id               - Unique ID generated by nanoid.
 * @property {string} user              - Owner user id.
 * @property {string} version           - Schema version of the dashboard.
 * @property {string} title             - Display title of the dashboard.
 * @property {string} visibility        - Visibility state (`private|link|public`).
 * @property {string} shareToken        - Opaque token for share-link access.
 * @property {{userId: string, accessLevel: string}[]} acl - Per-dashboard ACL entries.
 * @property {string} [image]           - Optional URL of dashboard thumbnail.
 * @property {Object[]} [datasources]   - Array of datasource configurations.
 * @property {number} [columns]         - Number of layout columns.
 * @property {string} [width='md']      - Layout width specifier (default: 'md').
 * @property {Object[]} [panes]         - Pane configurations.
 * @property {Object[]} [authProviders] - Authentication provider settings.
 * @property {Object} [settings]        - Miscellaneous dashboard settings.
 * @property {Date} createdAt           - Creation timestamp.
 * @property {Date} updatedAt           - Last update timestamp.
 */

/**
 * Mongoose schema for Dashboard.
 *
 * @type {MongooseSchema}
 */
const DashboardSchema = new Schema(
  {
    _id: {
      type: String,
      default: () => nanoid(),
    },
    user: {
      type: String,
      ref: "User",
      required: true,
      index: true,
    },
    version: {
      type: String,
      required: true,
    },
    title: {
      type: String,
      required: true,
    },
    visibility: {
      type: String,
      required: true,
      enum: DASHBOARD_VISIBILITIES,
      default: "private",
      index: true,
    },
    shareToken: {
      type: String,
      required: true,
      unique: true,
      index: true,
      default: generateShareToken,
    },
    acl: {
      type: [
        {
          userId: {
            type: String,
            required: true,
          },
          accessLevel: {
            type: String,
            required: true,
            enum: DASHBOARD_ACCESS_LEVELS,
          },
          grantedBy: {
            type: String,
            required: false,
            default: null,
          },
          grantedAt: {
            type: Date,
            required: true,
            default: Date.now,
          },
        },
      ],
      required: true,
      default: [],
    },
    image: {
      type: String,
      required: false,
    },
    datasources: {
      type: [Object],
      required: false,
    },
    columns: {
      type: Number,
      required: false,
    },
    width: {
      type: String,
      required: false,
      default: "md",
    },
    panes: {
      type: [Object],
      required: false,
    },
    authProviders: {
      type: [Object],
      required: false,
    },
    settings: {
      type: Object,
      required: false,
    },
  },
  {
    timestamps: true,
  }
);

DashboardSchema.index({ "acl.userId": 1 });

/**
 * Mongoose model for Dashboard.
 *
 * @type {MongooseModel}
 */
export default mongoose.model("Dashboard", DashboardSchema);
