/**
 * @module models/Dashboard
 * @description Mongoose schema and model for user dashboards in the Freeboard application.
 *  - Uses `nanoid` for unique dashboard IDs
 *  - Stores dashboard layout, settings, and metadata
 *  - Tracks creation and update timestamps automatically
 */

import mongoose from "mongoose";
import { ObjectId } from "mongodb";
import { nanoid } from "nanoid";

/**
 * @typedef {Object} MongooseSchema
 *   Alias for mongoose.Schema
 * @typedef {Object} MongooseModel
 *   Alias for mongoose.Model
 */

const Schema = mongoose.Schema;

/**
 * Ensure ObjectId valueOf returns string representation.
 */
ObjectId.prototype.valueOf = function () {
  return this.toString();
};

/**
 * Dashboard document schema.
 *
 * @typedef {Object} DashboardDoc
 * @property {string} _id               - Unique ID generated by nanoid.
 * @property {string} user              - Reference to owning user (_id of User).
 * @property {string} version           - Schema version of the dashboard.
 * @property {string} title             - Display title of the dashboard.
 * @property {boolean} published        - Whether the dashboard is public.
 * @property {string} [image]           - Optional URL of dashboard thumbnail.
 * @property {Object[]} [datasources]   - Array of datasource configurations.
 * @property {number} [columns]         - Number of layout columns.
 * @property {string} [width='md']      - Layout width specifier (default: 'md').
 * @property {Object[]} [panes]         - Pane configurations.
 * @property {Object[]} [authProviders] - Authentication provider settings.
 * @property {Object} [settings]        - Miscellaneous dashboard settings.
 * @property {Date} createdAt           - Creation timestamp.
 * @property {Date} updatedAt           - Last update timestamp.
 */

/**
 * Mongoose schema for Dashboard.
 *
 * @type {MongooseSchema}
 */
const DashboardSchema = new Schema(
  {
    _id: {
      type: String,
      default: () => nanoid(), // Generate unique ID using nanoid
    },
    user: {
      type: String,
      ref: "User", // Reference to User model
      required: true,
    },
    version: {
      type: String,
      required: true,
    },
    title: {
      type: String,
      required: true,
    },
    published: {
      type: Boolean,
      required: true,
    },
    image: {
      type: String,
      required: false,
    },
    datasources: {
      type: [Object],
      required: false,
    },
    columns: {
      type: Number,
      required: false,
    },
    width: {
      type: String,
      required: false,
      default: "md",
    },
    panes: {
      type: [Object],
      required: false,
    },
    authProviders: {
      type: [Object],
      required: false,
    },
    settings: {
      type: Object,
      required: false,
    },
  },
  {
    timestamps: true, // Adds createdAt and updatedAt fields
  }
);

/**
 * Mongoose model for Dashboard.
 *
 * @type {MongooseModel}
 */
export default mongoose.model("Dashboard", DashboardSchema);
